# 2.1.2 集合操作函数

* **async.each(arr,iterator(item, callback),callback)**

对数组arr中的每一项执行iterator操作。iterator方法中会传一个当前执行的项及一个回调方法。**each方法中所有对象是并行执行的**。对数组中每一项进行 iterator 函数处理，如果有一项出错则最终的回调的 err 就回事该 err。但是，出错并不会影响到其他的数组元素执行。

```js
const async = require('async')
const fs = require('fs')
let arr = ['./Test/file1.txt',"./Test/file2.txt","./Test/file3.txt"]
let iterator = (item,callback)=>{   
        fs.readFile(item,"utf-8",(err,results)=>{
            if(item === "./Test/file2.txt"){
                callback(new Error('wrong'))
            }else{
                console.log(results);
                callback(null,results)
            }          
        })      
}
async.each(arr,iterator,function(err){
    if(err){
        console.log(err)
    }
})
```

打印结果：

```
3
Error: wrong
    at fs.readFile (/Users/liulei/Desktop/asyncEach/test.js:10:26)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
1
```

可见，由于并发的原因，即是第二项出错，也不会影响其余的元素执行。如果想要让数组中的元素按照顺序执行，并且一旦一个出错，后面的数组元素都将不会执行的情况应该用另一个函数 **`async.eachSeeries(arr,iterator(item, callback),callback)`**,用法什么的都一样，这里就不赘述了。

此外，each方法的最终回调函数可以看出来的是，并不会被传入任何结果，所以**最终的回调函数就只有一个参数那就是 err**，如果想要向最终回调函数中传入某些结果那么还要用到接下来介绍的 `asycnc.map()`

* **async.map(arr,iterator(item, callback),callback)**

map方法使用方式和each完全一样，与each方法不同的是，map方法用于操作对象的转换，转换后的新的结果集会被传递至最终回调方法中（不出错的情况下）呈现一个新的数组的形似。

同样的是，map也是并行操作，如需按顺序并且出错就停止则需要使用 `async.mapSeries`